# Generated by the VisualDSP++ IDDE

# Note:  Any changes made to this Makefile will be lost the next time the
# matching project file is loaded into the IDDE.  If you wish to preserve
# changes, rename this file and run it externally to the IDDE.

# The syntax of this Makefile is such that GNU Make v3.77 or higher is
# required.

# The current working directory should be the directory in which this
# Makefile resides.

# Supported targets:
#     mcvsd_test_Debug
#     mcvsd_test_Debug_clean

# Define this variable if you wish to run this Makefile on a host
# other than the host that created it and VisualDSP++ may be installed
# in a different directory.

ADI_DSP=D:\Program Files\Analog Devices\VisualDSP 5.0


# $VDSP is a gmake-friendly version of ADI_DIR

empty:=
space:= $(empty) $(empty)
VDSP_INTERMEDIATE=$(subst \,/,$(ADI_DSP))
VDSP=$(subst $(space),\$(space),$(VDSP_INTERMEDIATE))

RM=cmd /C del /F /Q

#
# Begin "mcvsd_test_Debug" configuration
#

ifeq ($(MAKECMDGOALS),mcvsd_test_Debug)

mcvsd_test_Debug : ./Debug/mcvsd_test.dxe 

./Debug/code_mcvsd.doj :./code_mcvsd.asm 
	@echo ".\code_mcvsd.asm"
	$(VDSP)/easmblkfn.exe .\code_mcvsd.asm -proc ADSP-BF533 -file-attr ProjectName=mcvsd_test -g -o .\Debug\code_mcvsd.doj -MM

./Debug/decode_mcvsd.doj :./decode_mcvsd.asm 
	@echo ".\decode_mcvsd.asm"
	$(VDSP)/easmblkfn.exe .\decode_mcvsd.asm -proc ADSP-BF533 -file-attr ProjectName=mcvsd_test -g -o .\Debug\decode_mcvsd.doj -MM

Debug/test.doj :test.c mds_def.h coder.h fir_coeff.h voice_input.h 
	@echo ".\test.c"
	$(VDSP)/ccblkfn.exe -c .\test.c -file-attr ProjectName=mcvsd_test -g -structs-do-not-overlap -no-multiline -double-size-32 -decls-strong -warn-protos -proc ADSP-BF533 -o .\Debug\test.doj -MM

./Debug/mcvsd_test.dxe :$(VDSP)/Blackfin/ldf/adsp-BF533.ldf $(VDSP)/Blackfin/lib/bf532_rev_0.5/crtsf532y.doj ./Debug/code_mcvsd.doj ./Debug/decode_mcvsd.doj ./Debug/test.doj $(VDSP)/Blackfin/lib/bf532_rev_0.5/__initsbsz532.doj $(VDSP)/Blackfin/lib/cplbtab533.doj $(VDSP)/Blackfin/lib/bf532_rev_0.5/crtn532y.doj $(VDSP)/Blackfin/lib/bf532_rev_0.5/libsmall532y.dlb $(VDSP)/Blackfin/lib/bf532_rev_0.5/libio532y.dlb $(VDSP)/Blackfin/lib/bf532_rev_0.5/libc532y.dlb $(VDSP)/Blackfin/lib/bf532_rev_0.5/librt_fileio532y.dlb $(VDSP)/Blackfin/lib/bf532_rev_0.5/libevent532y.dlb $(VDSP)/Blackfin/lib/bf532_rev_0.5/libcpp532y.dlb $(VDSP)/Blackfin/lib/bf532_rev_0.5/libf64ieee532y.dlb $(VDSP)/Blackfin/lib/bf532_rev_0.5/libdsp532y.dlb $(VDSP)/Blackfin/lib/bf532_rev_0.5/libsftflt532y.dlb $(VDSP)/Blackfin/lib/bf532_rev_0.5/libetsi532y.dlb $(VDSP)/Blackfin/lib/bf532_rev_0.5/Debug/libssl532y.dlb $(VDSP)/Blackfin/lib/bf532_rev_0.5/Debug/libdrv532y.dlb $(VDSP)/Blackfin/lib/bf532_rev_0.5/Debug/libusb532y.dlb $(VDSP)/Blackfin/lib/bf532_rev_0.5/libprofile532y.dlb 
	@echo "Linking..."
	$(VDSP)/ccblkfn.exe .\Debug\code_mcvsd.doj .\Debug\decode_mcvsd.doj .\Debug\test.doj -L .\Debug -add-debug-libpaths -flags-link -od,.\Debug -o .\Debug\mcvsd_test.dxe -proc ADSP-BF533 -MM

endif

ifeq ($(MAKECMDGOALS),mcvsd_test_Debug_clean)

mcvsd_test_Debug_clean:
	-$(RM) ".\Debug\code_mcvsd.doj"
	-$(RM) ".\Debug\decode_mcvsd.doj"
	-$(RM) "Debug\test.doj"
	-$(RM) ".\Debug\mcvsd_test.dxe"
	-$(RM) ".\Debug\*.ipa"
	-$(RM) ".\Debug\*.opa"
	-$(RM) ".\Debug\*.ti"
	-$(RM) ".\Debug\*.pgi"
	-$(RM) ".\*.rbld"

endif


