/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.6 and the Signal Processing Toolbox 6.9.
 *
 * Generated on: 31-Oct-2011 23:38:40
 *
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 4
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2008a\extern\include\tmwtypes.h 
 */
const int BL = 4;
const real64_T B[4] = {
     0.2492067994122, 0.003196855657113, 0.003196855657113,   0.2492067994122
};
